admin-app/app/routes/cars.py
from datetime import datetime
from flask import Blueprint, request, redirect, url_for, render_template, current_app, flash, session
from pushbullet import Pushbullet
from app.services.car_service import CarService
from app.services.booking_service import BookingService
from app.gassistant.assistant import AspenAssistant

bp = Blueprint("cars", __name__, url_prefix="/cars")

@bp.route("/")
def list_cars():
    """
    Defines URL/route for displaying cars. Retrieves cars (stored in 
    cloud database) and routes to html page: '/cars'.

    :return: html page to display all cars
    :rtype: flask template 
    """
    key = current_app.config['GOOGLE_API_KEY']
    service = CarService()
    cars = service.search_cars({})
    return render_template("cars.html", cars=cars, key=key)

@bp.route("/reported")
def list_cars_reported_with_issues():
    """
    Defines URL/route for cars with reported issues. Retrieves cars 
    (stored in cloud database) with the status 'hasIssue',
    and routes to appropriate html page '/cars/reported'. Cars are 
    assigned this status when they need an engineer to fix them. 

    :return: html page displaying all cars with status 'hasIssue'
    :rtype: flask template
    """
    cars = CarService().search_cars({"car_status": "hasIssue"})
    pb_channel = current_app.config.get("PUSHBULLET_CHANNEL", "")
    return render_template("reported_cars.html", cars=cars, 
                            pb_channel=pb_channel)

@bp.route("/", methods=["POST"])
def search_cars():
    """
    Provides logic for filtering/searching displayed cars according to 
    their attributes/fields. Retrieves search terms from webpage
    and then matching cars (from cloud database) and routes to '/cars'.

    :return: html displaying all cars matching search terms
    :rtype: flask template
    """
    key = current_app.config['GOOGLE_API_KEY']
    fields = ["car_id", "year_from", "year_to", "car_model", "body_type", 
              "num_seats_from", "num_seats_to", "car_colour", 
              "cost_hour_from", "cost_hour_to"]
    types = [int, int, int, str, str, int, int, str, float, float]
    # transform/clean search dict
    searchD = {k: request.form[k] for k in fields}
    searchD = {k: (t(searchD[k]) if searchD[k] else "") for k,t in zip(fields, types)}
    for rangeK in ("year", "num_seats", "cost_hour"):
        fromK = rangeK + "_from"
        toK = rangeK + "_to"
        searchD[rangeK] = [searchD.pop(fromK), searchD.pop(toK)]
        if searchD[rangeK][0] == searchD[rangeK][1]:
            searchD[rangeK] = searchD[rangeK][0]
    searchD = {k: v for k,v in searchD.items() if v}

    user_speech = request.form.get("user_google_input")

    # call CarService to search for cars, providing search dict
    cars = CarService().search_cars(searchD)
    return render_template("cars.html", cars=cars, key=key, u_input=user_speech)

@bp.route("/<int:car_id>/map")
def map(car_id):
    """
    Display car location according to passed car ID (via URL)
    and displays car on map utilising google api. 
    Routes to '/cars/carID/map'. 

    :param car_id: ID/primary key of cars in car table
    :type car_id: int
    :return: html displaying car location matching car ID
    :rtype: flask template
    """
    car = CarService().get_car(car_id)
    key = current_app.config['GOOGLE_API_KEY']
    return render_template("map.html", key=key, car=car, 
                            back_to=request.args.get("back_to"))

@bp.route("/add")
def add_car_page():
    """
    Defines URL/route for add car page, '/cars/add'.

    :return: html for add car form
    :rtype: flask template
    """
    return render_template("addCar.html")

@bp.route("/add", methods=["POST"])
def add_car():
    """Provides logic (via POST) to retrieve data entered by user on 
    the add car page and sends this data to database.

    :return: confirmation message, redirects user to main menu
    :rtype: flask template
    """
    service = CarService()
    fields = ['year', 'car_model', 'body_type', 'num_seats', 'car_colour', 'cost_hour', 'latitude', 'longitude']
    data = {"car_status": "available"}
    for k in fields:
        if request.form[k]:
            data[k] = request.form[k]
    print(data)
    service.add_car(data)
    flash("Success! Car created")
    return render_template('menu.html')


@bp.route("/<int:car_id>/bookings")
def rental_history(car_id):
    """
    Defines URL/route: '/cars/car ID/bookings' and retrieves booking 
    history for car associated with Car ID, to display rental history.

    :param car_id: ID/primary key of cars in car table
    :type car_id: int
    :return: html for rental history of car
    :rtype: flask template
    """
    '''display all bookings made for specific car'''
    service = BookingService()
    bookings = service.get_bookings_for_car(car_id)
    return render_template('carHistory.html', car_id=car_id, 
                            bookings=bookings)


@bp.route("/<int:car_id>/update")
def update_car_page(car_id):
    """
    Defines URL/route: '/cars/car ID/update' for updating attributes of
    car, stored in database (except car ID). 

    :param car_id: ID/primary key of cars in car table
    :type car_id: int
    :return: html for update car page
    :rtype: flask template
    """
    #get current car details
    car = CarService().get_car(car_id)
    for k in list(car.keys()):
        if car[k] is None:
            car[k] = ""
    #return template with car details attached
    return render_template('updateCar.html', car=car)

@bp.route("/<int:car_id>/update", methods=["POST"])
def update_car(car_id):
    """
    Provides the logic to retrieve car field information from update car
    page and sends to database. Redirects user to main search page for
    cars.

    :param car_id: ID/primary key of cars in car table
    :type car_id: int
    :return: confirmation message, returns to main car list
    :rtype: flask template
    """
    service = CarService()
    #store data in dict for transmission
    data = {
        'year': request.form['year'],
        'car_model': request.form['car_model'],
        'body_type': request.form['body_type'],
        'num_seats': request.form['num_seats'],
        'car_colour': request.form['car_colour'],
        'cost_hour': request.form['cost_hour'],
        'car_status': request.form['car_status']
    }
    for k in ('latitude', 'longitude'):
        if request.form[k]:
            data[k] = request.form[k]
    service.update_car(car_id, data)
    flash(f"Success! Car #{car_id} details updated")
    return redirect(url_for('cars.list_cars'))


@bp.route("/<int:car_id>/remove", methods=["GET"])
def remove_car(car_id):
    """
    Defines URL/route to remove car: '/cars/car ID/remove'. Removes car
    from database and updates display accordingly. 

    :param car_id: ID/primary key of cars in car table
    :type car_id: int
    :return: updated list of cars
    :rtype: flask template
    """
    #pop up window asking for confirmation
    service = CarService()
    if service.delete_car(car_id):
        return redirect(url_for('cars.list_cars'))
    else:
        flash(f"Car #{car_id} could not be deleted")
        return redirect(url_for('cars.list_cars'))

@bp.route("/<int:car_id>/report")
def report_car_with_issue(car_id):
    """
    Defines route to report a car as having an issue and send pushbullet 
    notification to engineer alerting them that thier services are required.
    Updates database car status to 'hasIssue'.  

    :param car_id: ID/primary key of cars in car table
    :type car_id: int
    :return: html page listing cars with status of car updated
    :rtype: flask template
    """
    car_svc = CarService()
    pb = Pushbullet(current_app.config["PUSHBULLET_KEY"])
    car_channel = [c for c in pb.channels if c.name == current_app.config["PUSHBULLET_CHANNEL"]][0]
    response = car_channel.push_note(f"Car #{car_id} Issues", f"Car #{car_id} is reported with issues at {datetime.now().isoformat()}")
    car_svc.report_car_with_issue(car_id)
    return redirect(url_for("cars.list_cars"))


@bp.route("/makeassistant")
def makeassistant():
    #assistant = AspenAssistant()
    #session['assistant'] = jsonpickle.encode(assistant)
    return {"success" : "true"}

@bp.route("/voicesearch")
def voicesearch():
    assistant = AspenAssistant()
    data = assistant.assist()
    return data

admin-app/app/routes/dashboard.py
from collections import Counter
from datetime import timedelta
from flask import Blueprint, request, render_template, jsonify
from app.services.car_service import CarService
from app.services.user_service import UserService
from app.services.booking_service import BookingService

bp = Blueprint("dashboard", __name__, url_prefix="/dashboard")

@bp.route("/")
def dashboard():
    """
    Defines URL/route for dashboard: '/dashboard' which managers view on
    logging into employee website. 

    :return: html page for dashboard 
    :rtype: flask template
    """
    return render_template("dashboard.html")

@bp.route("/data/car_usage")
def car_usage():
    """
    Defines URL/route '/dashboard/data/car_usage' which displays number 
    of cars being used each day. Retrieves bookings data from cloud 
    database and transforms for display in graph.

    :return: car usage data in json form
    :rtype: flask Response object 
    """
    bk_svc = BookingService()
    bookings = bk_svc.search_bookings({})
    counter = Counter()
    for bk in bookings:
        bk_svc.transform_date(bk)
        curr = bk["date_booking"]
        while curr <= bk["date_return"]:
            date_s = bk_svc.gen_date_str(curr)
            counter[date_s] += 1
            curr += timedelta(days=1)
    data = []
    for k, n in counter.items():
        data.append({"date": k, "n_cars": n})
    return jsonify(data)

@bp.route("/data/revenue")
def rental_revenue():
    """
    Defines URL/route '/dashboard/data/revenue' which displays the daily
    revenue from renting cars. Retrieves booking history from cloud database
    and calculates amount of time cars have been rented for and resultant
    revenue. 

    :return: revenue data in json form
    :rtype: flask response object
    """
    bk_svc = BookingService()
    bookings = bk_svc.get_all_with_cars()
    counter = Counter()
    for bk in bookings:
        bk_svc.transform_date(bk)
        bk_svc.transform_time(bk)
        delta = bk["date_return"] - bk["date_booking"] + bk["time_return"] - bk["time_booking"]
        hours = delta.seconds / timedelta(hours=1).seconds
        date_s = bk_svc.gen_date_str(bk["date_return"])
        counter[date_s] += hours * bk["cost_hour"]
    data = []
    for k, n in counter.items():
        data.append({"date": k, "revenue": n})
    data.sort(key=lambda d: d["date"])
    # accumulative
    for i in range(1, len(data)):
        data[i]['revenue'] += data[i-1]["revenue"]
    return jsonify(data)

@bp.route("/data/user_activities")
def user_activities():
    """
    Defines URL/route '/dashboard/data/user_activities which displays
    number of active users each day. Information retrieved from cloud
    database table user_activity 

    :return: number of active user/day is json form
    :rtype: flask response object
    """
    type_counts = UserService().get_activity_types()
    return jsonify(type_counts)

admin-app/app/routes/users.py
from flask import Blueprint, request, render_template, redirect, url_for, session, flash
from passlib.hash import sha256_crypt
from app.services.user_service import UserService

bp = Blueprint("users", __name__, url_prefix="/users")

@bp.route("/")
def list_users():
    """
    Defines URL/route for displaying users. Retrieves users (stored in 
    cloud database) and routes to html page: '/users'.

    :return: html page to display all users
    :rtype: flask template 
    """
    users = UserService().get_all_users()
    return render_template('users.html', users=users)

@bp.route("/", methods=["POST"])
def search_users():
    """
    Provides logic for filtering/searching displayed users according to 
    their attributes/fields. Retrieves search terms from webpage
    and then matching users (from cloud database) and routes to '/users'.

    :return: html displaying all users matching search terms
    :rtype: flask template
    """
    fields = ["username", "fName", "lName", "email"]
    types = [str, str, str, str]
    #transform and clean dict for search 
    searchDict = {k: request.form[k] for k in fields}
    searchD = {k: v for k,v in searchDict.items() if v}
    # call UserService to search for users, providing search dict
    users = UserService().search_users(searchD)
    return render_template("users.html", users=users)

@bp.route("/<string:username>/update_form", methods=["GET"])
def update_user_page(username):
    """
    Defines URL/route: '/users/username/update' for updating the 
    attributes/fields of a user (except username). Retrieves original 
    user details from cloud database for display and editing.

    :param username: username=primary key for users in user table
    :type username: string
    :return: html for update user page
    :rtype: flask template
    """
    #get user details
    user = UserService().findExistingUser(username)
    #return template with user details attached
    return render_template('updateUser.html', user=user)

@bp.route("/<string:username>/update", methods=["POST"])
def update_user(username):
    """
    Provides logic to retrieve edited details from update user form, and
    then insert in database. If password is changed, hashes password
    and stores hash. Redirects to list of users after update. 

    :param username: username=primary key for user in user table
    :type username: string
    :return: Confirmation message, redirects to user view/search page.
    :rtype: flask template
    """
    #get current user details in order to retain password if needed
    service = UserService()
    data = {
        'fName': request.form['fname'],
        'lName': request.form['lname'],
        'email': request.form['email']
    }
    if request.form["password"] != "":
        data["password"] = sha256_crypt.using(rounds=1000).hash(request.form["password"])
    # call user service to send new user value
    service.update_user(username, data)
    flash(f"successfully updated user: {username}")
    return redirect(url_for("users.list_users"))


@bp.route("/<string:username>/remove", methods=["GET"])
def remove_user(username):
    """
    Defines route to remove user: '/users/username/remove'. Removes 
    user from database and updates user list accordingly. 

    :param username: username=primary key for user in user table
    :type username: string
    :return: updated list of users
    :rtype: flask template
    """
    '''remove user from database and update displays accordingly'''
    #pop up window asking for confirmation
    service = UserService()
    if service.delete_user(username):
        return redirect(url_for('users.list_users'))
    else:
        flash(f"{username} could not be deleted")
        return redirect(url_for('users.list_users'))

@bp.route("/add")
def add_user_page():
    """
    Defines URL/route for add car page, '/cars/add'.

    :return: html for add car form
    :rtype: flask template
    """
    return render_template('addUser.html')

@bp.route("/add", methods=["POST"])
def add_user():
    """
    Provides logic (via POST) to retrieve data entered on the add user 
    page. Confirms entered username is unique, and prompts for different
    username if not. Data is then sent to cloud database to create a new 
    record in user table. 

    :return: confirmation message user was added, redirects to main menu
    :rtype: flask template
    """
    service = UserService()
    username = request.form['username']
    usernameTaken = service.findExistingUser(username)
    if usernameTaken is not None:
        flash(f"Username {username} is already taken. Please try again")
        return render_template('addUser.html')
    else:
        password = request.form['password']
        pwHash = sha256_crypt.using(rounds=1000).hash(password)
        data = {
            'username': username,
            'password': pwHash,
            'fName': request.form['fname'],
            'lName': request.form['lname'],
            'email': request.form['email']
        }
        result = service.add_user(data)
        if result is not None:
            flash(f"Success! User {username} created ")
            return render_template('menu.html')
    

admin-app/app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block navbar %}
{% if session["role"] == "manager" %}
    <nav class="navbar navbar-inverse" style="background-color:darkgreen;">
{% elif session["role"] == "admin" %}
<nav class="navbar navbar-dark bg-primary" style="background-color:rgb(35, 9, 61);">
{% elif session["role"] == "engineer" %}
    <nav class="navbar navbar-dark bg-primary" style="background-color:rgb(81, 36, 81);">
{% else %}
<nav class="navbar navbar-inverse">
{% endif %}
    <div class="container-fluid">
        <ul class="nav navbar-nav navbar-left">
            {% if session["loggedIn"] %}
                {% if session["role"] == "manager" %}
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('dashboard.dashboard') }}">Dashboard</a></li>
                {% elif session["role"] == "admin" %}
                    <li><a href="{{ url_for('cars.list_cars') }}">Cars</a></li>
                    <li><a href="{{ url_for('users.list_users') }}">Users</a></li>
                {% else %}
                    <li><a href="{{ url_for('cars.list_cars_reported_with_issues') }}">Reported Cars</a></li>
                {% endif %}
            {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if session['loggedIn'] %}
            <li><span class="navbar-text">Welcome, {{ session['fName'] }}</span> </li>
            <li><a href="{{ url_for('employees.logout') }}">Logout</a></li>
            {% else %}
            <li><a href="{{ url_for('employees.login') }}">Login</a></li>
            {% endif %}
            {% if session['role'] == 'admin' %}
                <li><a href="{{ url_for( 'employees.menu') }}">Main Menu</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

{% endblock navbar %}

{% block error_message %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="container">
                    <div class="alert {{ 'alert-success' if 'success' in message.lower() else 'alert-danger' }}">
                        {{ message }}
                    </div> 
                </div>
            {% endfor %} 
        {% endif %}
    {% endwith %}
{% endblock %}

admin-app/app/templates/dashboard.html
{% extends 'base.html' %}

{% block scripts %}
    {{super()}}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.26.0/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.js"></script>
    <script src="{{url_for('static', filename='util.js')}}"></script>
    <script src="{{url_for('static', filename='chart_factory.js')}}"></script>

    <script>
        let myChart;
        $("#car_usage_link").click(function(event) {
            if (myChart)
                myChart.destroy();
            $.ajax({
                url: "{{ url_for('dashboard.car_usage') }}",
            }).done(function(car_usage_raw) {
                console.log("car usage raw data: ");
                console.log(car_usage_raw);
                const data = [];
                car_usage_raw.forEach(function(item, index, array) {
                    data.push({
                        x: item["date"],
                        y: item["n_cars"]
                    });
                });
                myChart = generate_date_bar_chart("chart_cvs", data);
            });
        });
        $("#revenue_link").click(function(event) {
            if (myChart)
                myChart.destroy();
            $.ajax({
                url: "{{ url_for('dashboard.rental_revenue') }}"
            }).done(function(raw_data) {
                console.log("raw revenue data:");
                console.log(raw_data);
                const data = [];
                raw_data.forEach(function(item, index, array) {
                    data.push({
                        x: item["date"],
                        y: item["revenue"]
                    });
                });
                myChart = generate_date_revenue_line_chart("chart_cvs", data);
            })
        });
        $("#user_activities").click(function(event) {
            if (myChart)
                myChart.destroy();
            $.ajax({
                url: "{{ url_for('dashboard.user_activities') }}"
            }).done(function(raw_data) {
                console.log("raw user activity data:");
                console.log(raw_data);
                const data = [];
                const labels = [];
                raw_data.forEach(function(item, index, array) {
                    data.push(item["count"]);
                    labels.push(item["activity"]);
                });
                myChart = generate_activity_polar_area("chart_cvs", data, labels);
            });
        });
    </script>

{% endblock %}

{% block content %}
<div class="text-center container">
    <ul class="nav nav-tabs">
        <li class="nav-item col-sm">
            <a class="nav-link" href="#" id="car_usage_link">Car Usage</a>
        </li>
        <li class="nav-item col-sm">
            <a class="nav-link" href="#" id="revenue_link">Revenue</a>
        </li>
        <li class="nav-item col-sm">
            <a class="nav-link" href="#" id="user_activities">User Activities</a>
        </li>
    </ul>
</div>

<div class="container">
    <canvas id="chart_cvs"></canvas>
</div>

{% endblock %}

admin-app/app/templates/index.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel heading text-center">
                <h2><i>Welcome to </i><strong>Sharing is Car(ing)</strong></h2>
                <h2><strong>Employee Portal</strong></h2>
            </div>
            <div class="panel body text-center">
                <div class="row">
                    <img class="img-fluid" width="20%" src="{{ url_for('static', filename='car_system.png') }}">
                </div>
                <div class="btn-group btn-group btn-group-lg">
                    {% if not session['loggedIn'] %}
                    <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for( 'employees.login') }}';">Login</button>
                    {% else %}
                        {% if session['role'] == 'admin' %}
                            <button type="button" class="btn btn-info" onclick="window.location.href='{{ url_for( 'employees.menu') }}';">Main Menu</button>
                        {% endif %}
                        {% if session['role'] == 'manager' %}
                            <button type="button" class="btn btn-info" onclick="window.location.href='{{ url_for( 'dashboard.dashboard') }}';">Dashboard</button>
                        {% endif %}
                        {% if session['role'] == 'engineer' %}
                            <button type="button" class="btn btn-info" onclick="window.location.href='{{ url_for( 'cars.list_cars_reported_with_issues') }}';">Reported Cars</button>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

admin-app/app/templates/menu.html
{% extends "base.html" %}

{% block title %}
Menu
{% endblock title %}

{% block content %}
{% block error_message %}
{{ super() }}
{% endblock %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel heading text-center">
                <h2><strong>Main Menu</strong></h2>
            </div>
            <div class="panel body text-center">
                <div class="btn-group btn-group btn-group-lg">
                    {% if not session['loggedIn'] %}
                        <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for('employees.login') }}';">Login</button>
                  
                    {% else %}
                        <h4><strong>CARS</strong></h4>
                        <!--list of cars with search functionality-->
                        <div class="row">
                            <button type="button" class="btn btn-info" onclick="window.location.href='{{ url_for('cars.list_cars') }}';">View Cars</button><br>
                            <label >View Cars to search, view rental history, update, remove, or report an issue</label>
                            
                        </div>
                        <br>
                        <!--list of cars with reported issues-->
                        <div class="row">
                            <button type="button" class="btn btn-info" onclick="window.location.href='{{ url_for('cars.list_cars_reported_with_issues') }}';">View Cars with Reported Issues</button><br>
                        </div>
                        <br>
                         <!--add car-->
                        <div class="row">
                            <button type="button" class="btn btn-info" onclick="window.location.href='{{ url_for('cars.add_car_page') }}';">Add Car</button><br>
                        </div>
                        <br><br>
                        <h4><strong>USERS</strong></h4>
                        <!--list of users with search functionality-->
                        <div class="row">
                            <button type="button" class="btn btn-info" onclick="window.location.href='{{ url_for('users.list_users') }}';">View Users</button><br>
                            <label>View Users to search, update or remove</label><br>
                        </div>
                        <br>
                        <div class="row">
                            <button type="button" class="btn btn-info" onclick="window.location.href='{{ url_for('users.add_user_page') }}';">Add User</button><br>
                            <br>
                        </div>
                        <br>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{{ output }}
{% endblock %}

admin-app/app/templates/users.html
{% extends "base.html" %}

{% block title %}
    Users
{% endblock title %}

{% block content %}
    <div class="container">
        {% block error_message %}
            {{ super() }}
        {% endblock %}
        <div class="panel">
            <a class="btn btn-primary" href="{{ url_for('users.add_user_page') }}">Add a User</a>
        </div>
        <div class="panel">
            <h4>Search/Filter</h4>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                    <form method="post" action="{{ url_for('users.search_users') }}" id="search-user-form">
                        <div class="row">
                            <div class="form-group col-md-3">
                                <label class="control-label" for="username">Username</label>
                                <input class="form-control" type="text" id="username" name="username">
                            </div>
                            <div class="form-group col-md-3">
                                <label class="control-label" for="fName">First Name</label>
                                <input class="form-control" type="text" id="fName" name="fName">
                            </div>
                            <div class="form-group col-md-3">
                                <label class="control-label" for="lName">Last Name</label>
                                <input class="form-control" type="text" id="lName" name="lName">
                            </div>
                            <div class="form-group col-md-3">
                                <label class="control-label" for="email">Email Address</label>
                                <input class="form-control" type="email" id="email" name="email">
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-3">
                                <button type="submit" class="btn btn-primary" id="submit">Submit</button>
                                <button type="button" class="btn btn-light" onclick="window.location.href='{{ url_for('users.list_users') }}';">Clear Input</button>
                            </div>
                            <div class="form-group col-md-3">
                                
                            </div>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">        
            <div class="col-12">
                <div class="table-responsive">
                    <table class='table' style="width:100%">
                        <thead>
                            <tr>
                                <th>Username</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Email</th>
                                <th>Update</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for user in users %}
                            <tr>
                                <td>{{ user['username'] }}</td>
                                <td>{{ user['fName'] }}</td>
                                <td>{{ user['lName'] }}</td>
                                <td>{{ user['email'] }}</td>
                                <td><a href="{{ url_for('users.update_user_page', username=user['username']) }}">Update User Details</a> </td>
                                <td><a href="{{ url_for('users.remove_user', username=user['username']) }}" onclick="return confirm('Delete User? This action can not be undone.')">Delete User</a> </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}